### ISSUE TITLE
Problem with gcc file

### ISSUE THREAD

**Issue by markb41** [rstraver/wisecondor#17]
Hi Rstraver

I've created pickle files and gcc files and established reference samples. However when testing a new sample I run into problems with the gcc file as follows:
....
  Targeting chromosome:   22
                Calculating distances to chromosome:    1
                Calculating distances to chromosome:    2
                Calculating distances to chromosome:    3
                Calculating distances to chromosome:    4
                Calculating distances to chromosome:    5
                Calculating distances to chromosome:    6
                Calculating distances to chromosome:    7
                Calculating distances to chromosome:    8
                Calculating distances to chromosome:    9
                Calculating distances to chromosome:    10
                Calculating distances to chromosome:    11
                Calculating distances to chromosome:    12
                Calculating distances to chromosome:    13
                Calculating distances to chromosome:    14
                Calculating distances to chromosome:    15
                Calculating distances to chromosome:    16
                Calculating distances to chromosome:    17
                Calculating distances to chromosome:    18
                Calculating distances to chromosome:    19
                Calculating distances to chromosome:    20
                Calculating distances to chromosome:    21
                Calculating distances to chromosome:    22
                Picking reference bins
Writing reference to file
  File "/data/illumina/nipd/temptest5/140691.gcc", line 2
    S'20'
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/data/mark/tools/wisecondor/plot.py", line 164, in <module>
    sampleData = pickle.load(open(args.plotdata,'rb'))
IOError: [Errno 2] No such file or directory: '/data/illumina/nipd/NIPD1_1-36/140691.plot'

Do you have any idea of the course of this error and maybe even a solution to the problem?

best regards and thanks

Mark

**Comment by rstraver** [comment]
It looks like you jumped from creating a reference to trying to plot without running test.py in between, is this from running run.sh or did you run these steps manually?
This should happen: .pickle -> .gcc -> .plot -> .pdf
yours appears to be missing .gcc -> .plot, done by test.py

**Comment by markb41** [comment]
Thanks a lot for your help - my analysis is now running again without any errors.

**Comment by rstraver** [comment]
Cheers, glad to hear it works!
