### ISSUE TITLE
index error while running test.py

### ISSUE THREAD

**Issue by shawpa** [rstraver/wisecondor#18]
I am getting an error when I try to run test.py. I have no idea what this could mean so any suggestions would be appreciated. The following is the output that I get when I try and test a sample. 

Settings used:
binsize 1000000
maxrounds       5
outfile pl58.out.pickle
reference       reftable1234.pickle
refmaxbin       100
refmaxrep       3
refmaxval       1000000
refminbin       10
sample  pl58.gcc
smaxskip        2
sminbins        10
trithres        0.5
window  5
wmaxskip        1
wminbins        10

Processing:
Loading:        Sample: pl58.gcc
Loading:        Reference Table reftable1234.pickle

Determining reference cutoffs
        Cutoff determined:      0.142752999

/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/wisecondor-master/test.py", line 337, in <module>
    avgDev = checkAverageDeviation(sample,args.refminbin,args.refmaxbin,maxDist)
  File "/usr/local/bin/wisecondor-master/test.py", line 81, in checkAverageDeviation
    dev = numpy.std(reference)/numpy.median(reference)#sample[str(chrom)][bin]
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3084, in median
    overwrite_input=overwrite_input)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2997, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3138, in _median
    n = np.isnan(part[..., -1])
IndexError: index -1 is out of bounds for axis 0 with size 0

Thank you for your help.

**Comment by rstraver** [comment]
Hi again, this is rather difficult to troubleshoot I'm afraid. Is your sample extremely low coverage by any chance? And did you have any problems running other samples with the same settings and version previously?

**Comment by shawpa** [comment]
Sorry I didn't get back to you sooner but I was out yesterday. Thank you for looking into this. A while back I did run a number of samples. I just tried running a sample that I actually ran previously and got results previously. This time around it through an error. I believe that I am using the same version of wisecondor that I used before because I don't recall updating the program. I see that there is a new release so maybe updating it will fix this issue. The only thing that changed on this system from when I ran the test before and now was a new installation of matplotlib and biostatistics.lowess modules. Could version changes in those affect the running of test.py? Just for reference, I also tried running the exact files (sample and old reftable file) that I knew worked previously and the same error is appearing.

**Comment by shawpa** [comment]
I tried the updated version of wisecondor and I am still getting the same error. Please let me know what further information I can provide to you to help troubleshoot this issue.

**Comment by shawpa** [comment]
Just wanted to let you know that we fixed whatever the issue was on our end. I believe the problem was Numpy. In order to use the newest version of matplotlib, numpy also had to be updated. Seems like this newer version of numpy isn't compatible with your test.py script. We reverted back to the older versions provided on your wiki and it works now. Just wanted to let you know in case anyone has similar issues.

**Comment by rstraver** [comment]
Hi shawpa,

Thanks for letting me know. I was a tad too busy this week to solve it but indeed these packages seemed the only possible cause of the error. Could you tell me what versions of matplotlib and numpy exactly were incompatible? Might look into it if it turns out to be common.

**Comment by shawpa** [comment]
Since I don't do the installation I can't be 100% sure but it was most likely the newest version of matplotlib (1.5.0). That matplotlib version required numpy 1.10.0.

**Comment by rstraver** [comment]
Thanks, if the problem occurs to others as well I'll look into it.
