### ISSUE TITLE
how to prepare reads for NIPT ?

### ISSUE THREAD

**Issue by WinterLi1993** [rstraver/wisecondor#23]
Dear Author,
    I need to cut adapter sequence from single-end fastq of NIPT ? which tool should use ?

thank you !

**Comment by rstraver** [comment]
Hi, as we use 51bp single end fragments, the only adapters we should be worried about are already removed in the demultiplex stage. The reads are likely too short to hit adapter sequences on the other end of the fragment in most of the data, and the few that are left are generally dropped as they become unmappable. Are you using significantly longer reads? If not I'd suggest just going ahead and skipping adapter trimming.

**Comment by WinterLi1993** [comment]
HI, I  use 76 bp single end fragments , so need to cut adapter for single end ?

**Comment by rstraver** [comment]
I doubt you need to, assuming you did nothing strange in the sample preps most of the reads that are useful for further analysis should be longer than that. Whatever is not should be dropped out when you force BWA to map with 0 mismatches.
If you feel you should trim your data anyway, I don't think there would be any serious negative side effects for WISECONDOR as long as you apply it consistently on all your data.

**Comment by WinterLi1993** [comment]
HI ,  we need to cut adapter sequence  after thinking. Do you have any recommended tool to cut adapter ?

**Comment by rstraver** [comment]
Well, the ones we know of are cutadapt or trimmomatic, but we can't really advise on how to use those or whether there are any better performing tools.

**Comment by WinterLi1993** [comment]
HI ,
   do you know how to  mask out parts of genome known to be of low complexity, e.g. the regions
flagged by repeatmasker or regions with low mappability. ?? 
 where  I can find such this region bed format file ??

thank you !

**Comment by rstraver** [comment]
I believe those are available as tracks on UCSC, not sure if they are in bed format though. Do you need them for WISECONDOR? Areas that are hard to work with should be identified and ignored automatically.

**Comment by WinterLi1993** [comment]
yep, I  wanna download that file ,and to understand better . can you show me some link to download ?
thank you !

**Comment by rstraver** [comment]
This is pretty much the best I can find right now, not in bed format though but you can probably find a way to apply them anyway:
http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/
Do note this one is for Hg19, other reference versions should have similar paths.

**Comment by WinterLi1993** [comment]
thank you ! 
I test a T18 sample, but the result showed me it's normal.... I do not know why ...I send you that sample's fastq  file ?

**Comment by rstraver** [comment]
Before we start sending boatloads of data, could you tell me how many samples you used to create your reference and what your output pdf looks like? Either upload it somewhere I can reach it or send it to r.straver@vumc.nl

Additionally, did you use run.sh, and what do the outputs for each step say?

**Comment by WinterLi1993** [comment]
HI, maybe I should keep  uniquely mapped reads from a bam file ?

**Comment by rstraver** [comment]
That wouldn't matter as the conversion step in run.sh should solve how to deal with those.

**Comment by WinterLi1993** [comment]
samtools rmdup -s sample.bam - | samtools view - -q 1, use this command ,we can keep uniquely mapped reads from a bam file  ?

**Comment by rstraver** [comment]
Yes, that removes duplicates and turns the data into readable text, do note the specific arguments used though and determine if those are fitting for your data:

```
rmdup
    -s      Remove duplicate for single-end reads. By default, the command works
                         for paired-end reads only.

view
    -q INT    Skip alignments with MAPQ smaller than INT [0]
```

**Comment by fengdong110** [comment]
If we did not remove duplication，Whether it will affect the detection results? We now duplication is 4% ？

**Comment by rstraver** [comment]
@fengdong110 In general I advise not mixing approaches (either remove duplicates from both reference and test data, or not). 

However, if you are using the latest version of WISECONDOR (the current master branch), the conversion checks and removes a read if subsequent reads start at the same basepair coordinate. So it shouldn't matter in this case, as WISECONDOR removes most likely duplications by itself.
