### ISSUE TITLE
Ion-wisecondor

### ISSUE THREAD

**Issue by dridk** [rstraver/wisecondor#24]
Hi, 
thanks for your scripts ! 
We made a plugin for the Ion torrent sequencer avaible there https://github.com/dridk/ion-wisecondor  . 
This plugin can be installed into the torrent server easily. 
Could you share this on your wikipage ?

**Comment by rstraver** [comment]
Hi, I put a link at the bottom of the wiki home:
https://github.com/rstraver/wisecondor/wiki

Thanks for letting me know and adding this!

**Comment by dridk** [comment]
No problem! Your algorithm is in production here ! At Brest city in France.
