### ISSUE TITLE
Extract chromosome coverage from .pickle files?

### ISSUE THREAD

**Issue by biocyberman** [rstraver/wisecondor#25]
Hi,
Some of my original bam files are broken. And I am not familiar with .pickle files. Could you show me how to extract number of reads mapped to each chromosome?

Thanks
Vang

**Comment by dridk** [comment]
pickle is a json serialisation file. 
You can easily read it using python. 

     import pickle
     with open("file.pickle", "r") as file:
           data = pickle.loads(file)
           print(data)

**Comment by rstraver** [comment]
I think @dridk's answer is pretty close, if you want just the total per chromosome this sums it as well, and takes the pickle file as an argument:
```
import pickle,sys
with open(sys.argv[1], "r") as fileName:
	data = pickle.load(fileName)
	for key in data:
		print key, sum(data[key]) 
```

Additionally I think file is a pre-defined term in python, better not overwrite that.

**Comment by biocyberman** [comment]
Oh that's easy. I will explore the data and see if I can fetch the chromosome coverage information. 
Thanks
