### ISSUE TITLE
Wisecondor run.sh script

### ISSUE THREAD

**Issue by smruti241** [rstraver/wisecondor#50]
I ran the run.sh script but it is giving me this error:
Directory structure
	Creating directory: GRCh37_latest_genomic.fna
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/GRCh37_latest_genomic.fna’: File exists
	Creating directory: NIPT/new_data/*.bam
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/NIPT/new_data/bwa_aln_006.bam’: File exists
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/NIPT/new_data/bwa_aln_007.bam’: File exists
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/NIPT/new_data/bwa_aln_008.bam’: File exists
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/NIPT/new_data/bwa_aln_009.bam’: File exists
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/NIPT/new_data/bwa_aln_010.bam’: File exists
	Creating directory: NIPT/new_data/bwa_aln_006.bam
mkdir: cannot create directory ‘/home/mdrcubuntu/Downloads/NIPT/new_data/bwa_aln_006.bam’: File exists

Reference data
	Missing: GRCh37_latest_genomic.fna/reference
ls: cannot access '/home/mdrcubuntu/Downloads/NIPT/new_data/*.bam/*': No such file or directory

Please provide several *.bam files in NIPT/new_data/*.bam/ obtained from healthy pregnancies. More samples yield better results.

Can you please guide me how to use this bash script.

**Comment by rstraver** [comment]
Based on the errors I guess you altered the script as it should just make some folders the first time it runs. If you are not comfortable editing Bash I'd suggest not altering the run.sh file at all and just running it and following the directions.
If you want it to run on a folder structure of your own you probably are better of just following the steps in the script yourself, this script is really meant to run in one way only as simplification/example.

**Comment by smruti241** [comment]
after running this script, I got this:
Reference data
	Missing: dataFiles/reference
ls: cannot access './/refSamples/*': No such file or directory


what does this mean? How shall I put the data into this folders?

**Comment by rstraver** [comment]
Did you remove any folders previously made by the script before running again? I think it got confused. It's complaining a folder that should have been made by the script just before isn't there. You may want to start cleanly by re-downloading the scripts in a new folder and just run the script from there.
Also, did you take a look at WisecondorX? That project is built upon the logic from this one but is more actively developed and supported.

**Comment by smruti241** [comment]
I tried with wisecondorX but I faced same issue. I raised an issue there also. Can you please answer to my query there?

**Comment by rstraver** [comment]
I didn't really develop on that directly so I'd be guessing as well, but based on the description I'd check what they asked for (sam or bam) first. If you run a `head file.bam` it should return nonsensical output if you really have a bam, but look fine if you'd run `samtools view -H file.bam`. If both look fine (and the same) it's a sam file. Might be that is indeed the issue there. If it really is a bam (jumbled result for the `head` command), try posting the result of `samtools view -H file.bam` there to show what references you have in the bamfile, there might be something off with that.
