### ISSUE TITLE
Regarding wisecondor.py convert

### ISSUE THREAD

**Issue by sneha1201** [rstraver/wisecondor#53]
Hello,

while using python wisecondor.py convert ./input/sample.bam ./output/sample.npz -binsize 50000

i am getting below mentioned error
##  File "wisecondor.py", line 27
    print 'Conversion finished'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Conversion finished')?

Sorry if this is a basic one , but i'm not able to figure out this one .
if someone can help me with this one it would be a great help.

**Comment by rstraver** [comment]
Your error suggests you are running using Python 3. Per the readme:
> WISECONDOR was developed and tested using Python2.7.

Additionally you may want to try a fork with more support instead:
> A fork of this project, named [WisecondorX](https://github.com/leraman/wisecondorX), includes the necessary changes to test these chromosomes as well.

I haven't been actively maintaining this repository for several years now so your best bet really is that fork.

**Comment by sneha1201** [comment]
Thanks this resolve my issue.

By changing python version and numpy the issue get resolved.
