### ISSUE TITLE
Question about inputs

### ISSUE THREAD

**Issue by NstVasileva** [rstraver/wisecondor#54]
Hello! 
Do I understand correctly that references and test are the same sample? And I need few references - different sequencing of this one sample. And test - another sequencing of this sample?

Or I need few sequencing of random samples... and test is another sequencing of one of the references samples?

**Comment by rstraver** [comment]
Hi,
While testing is done within a sample, a model needs to be created using a training set of other (healthy) samples in advance. This training set should be various patients and sequencing runs for best results.

**Comment by NstVasileva** [comment]
Thank you!
